
extends: standard
#plugins: [ dependencies ]
rules:
  operator-linebreak: [ error, before ]
  object-curly-spacing: [ error, always ]
  array-bracket-spacing: [ error, always ]
  indent: [ error, 2, {
    flatTernaryExpressions: true
  }]
  padded-blocks: off
#  dependencies/case-sensitive: 1
#  dependencies/no-cycles: 1
#  dependencies/no-unresolved: 1
#  dependencies/require-json-ext: 1
